<a href="https://colab.research.google.com/github/kris0425821/python_list/blob/main/1_2_25.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv('Reviews.csv',nrows=500)
df.head(3)

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Id                      500 non-null    int64
 1   ProductId               500 non-null    object
 2   UserId                  500 non-null    object
 3   ProfileName             500 non-null    object
 4   HelpfulnessNumerator    500 non-null    int64
 5   HelpfulnessDenominator  500 non-null    int64
 6   Score                   500 non-null    int64
 7   Time                    500 non-null    int64
 8   Summary                 500 non-null    object
 9   Text                    500 non-null    object
dtypes: int64(5), object(5)
memory usage: 39.2+ KB

In [ ]:
df.Summary.head()

0    Good Quality Dog Food
1        Not as Advertised
2    "Delight" says it all
3           Cough Medicine
4              Great taffy
Name: Summary, dtype: object

In [ ]:
df.Text.head()

0    I have bought several of the Vitality canned d...
1    Product arrived labeled as Jumbo Salted Peanut...
2    This is a confection that has been around a fe...
3    If you are looking for the secret ingredient i...
4    Great taffy at a great price.  There was a wid...
Name: Text, dtype: object

In [ ]:
import nltk
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('Textblob')

In [ ]:
from string import punctuation
from nltk.corpus import stopwords
from textblob import TextBlob
from textblob import Word
df['Text'] = df['Text'].apply(lambda x: ''.join(x.lower() for x in x.split()))
df['Text'] = df['Text'].str.replace('[^\w\s]','')
stop=stopwords.words('english')
df['Text'] = df['Text'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
df['Text'] = df['Text'].apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()]))
df.Text.head()

0    ihaveboughtseveralofthevitalitycanneddogfoodpr...
1    productarrivedlabeledasjumbosaltedpeanuts...th...
2    thisisaconfectionthathasbeenaroundafewcenturie...
3    ifyouarelookingforthesecretingredientinrobitus...
4    greattaffyatagreatprice.therewasawideassortmen...
Name: Text, dtype: object

In [ ]:
from nltk.corpus import stopwords
from textblob import TextBlob
from textblob import Word
df['Text']=df['Text'].str.replace('[^\w\s]','')
stop=stopwords.words('english')
df['Text']=df['Text'].apply(lambda x: " ".join(x for x in x.split() if x not in stop))
df['Text']=df['Text'].apply(lambda x: str(TextBlob(x).correct()))
df['Text']=df['Text'].apply(lambda x: " ".join([Word(word).lemmatize() for word in x.split()]))
df.Text.head()

In [ ]:
reviews=df
reviews.dropna(inplace=True)
reviews.Score.hist(bins=5,grid=False)
plt.show()
print(reviews.groupby('Score').count().id)

In [ ]:
score_1=reviews[reviews['Score']==1.sample(n=18)]
score_2=reviews[reviews['Score']==2.sample(n=18)]
score_3=reviews[reviews['Score']==3.sample(n=18)]
score_4=reviews[reviews['Score']==4.sample(n=18)]
score_5=reviews[reviews['Score']==5.sample(n=18)]

In [ ]:
reviews.sample=pd.concat([score_1,score_2,score_3,score_4,score_5],axis=0)
reviews_sample.reset_index(drop=True,inplace=True)
print(reviews_sample.groupby('Score').count().id)

In [ ]:
from wordcloud import WordCloud=d
review_str="".join(review_sample["Summary"].to_numpy())
reviews_sample.Summary.str.cat()
wordcloud=WordCloud(background_color='white').generate(review_str)
plt.figure(figsize=(10,10))
plt.imshow(wordcloud,interpolation='bilinear')
plt.axis('off')
plt.show()